XCode.RuningCode/XCode.RuningCode.Web/Areas/Adm/Controllers/ControlController.cs
using System.Linq;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using XCode.RuningCode.Service.Abstracts;

namespace XCode.RuningCode.Web.Areas.Adm.Controllers
{
    public class ControlController : AdmBaseController
    {
        private readonly IUserService userService;
        public ControlController(IUserService userService)
        {
            this.userService = userService;
        }

        // GET: Adm/Control
        public ActionResult Index()
        {
            if (IsLogined)
            {
                //获取拥有的角色
                var userid = CurrentUser.Id;
                ViewBag.MyMenus = userService.GetMyNavigates(userid);
            }
            return View();
        }

        /// <summary>
        /// Welcome
        /// </summary>
        /// <returns></returns>
        public ActionResult Welcome()
        {
            return View();
        }
    }
}

XCode.RuningCode/XCode.RuningCode.Web/Controllers/ArticleController.cs
using System.Web.Mvc;
using System.Web.Security;
using XCode.RuningCode.Service.Abstracts;
using XCode.RuningCode.Service.Abstracts.Blog;
using XCode.RuningCode.Service.Dto.Blog;

namespace XCode.RuningCode.Web.Controllers
{
    public class ArticleController : Controller
    {
        private readonly ICategoryService categoryService;
        private readonly IArticleService articleService;
        private readonly ITagService tagService;
        private readonly IAuthorizeProvider provider;

        public ArticleController(ICategoryService category_service, IArticleService article_service, ITagService tag_service, IAuthorizeProvider provider)
        {
            categoryService = category_service;
            articleService = article_service;
            tagService = tag_service;
            this.provider = provider;
        }

        public ActionResult Add()
        {
            ViewBag.ParentCategory = categoryService.Query(item => !item.IsDeleted, item => item.Id, false);
            return View();
        }

        [HttpPost]
        public ActionResult Add(string moudleId, string menuId, string btnId, ArticleDto dto)
        {
            var user = provider.GetAuthorizeUser();
            var tag = tagService.Get();
            var category = categoryService.GetCategoryById(1);
            dto.Category = category;
            dto.Author = user;
            dto.Tags.Add(tag);
            articleService.Add(dto);
            return RedirectToAction("Index", "Blog");
        }
    }
}

XCode.RuningCode/XCode.RuningCode.Web/Controllers/BlogController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using XCode.RuningCode.Core.Enums;
using XCode.RuningCode.Service.Abstracts;
using XCode.RuningCode.Service.Abstracts.Blog;
using XCode.RuningCode.Service.Dto.Blog;

namespace XCode.RuningCode.Web.Controllers
{
    [AllowAnonymous]
    public class BlogController : Controller
    {
        private readonly ICategoryService categoryService;
        private readonly ITagService tagService;
        private readonly IArticleService articleService;
        private readonly IFriendlyLinkService friendly_link_service;
        private IAuthorizeProvider provider;
        private IUserService userService;

        public BlogController(ICategoryService categoryService, ITagService tagService, IArticleService articleService, IFriendlyLinkService friendlyLinkService, IAuthorizeProvider provider, IUserService userService)
        {
            this.categoryService = categoryService;
            this.tagService = tagService;
            this.articleService = articleService;
            friendly_link_service = friendlyLinkService;
            this.provider = provider;
            this.userService = userService;
        }

        public ActionResult Index(ArticleQueryType? type, int? id)
        {
            ViewBag.Categories = categoryService.Query(item => !item.IsDeleted, item => item.Id, false);
            var articleDtos = new List<ArticleDto>();
            if (type == null || type == ArticleQueryType.Article || id == null)
            {
                articleDtos = articleService.Query(item => !item.IsDeleted, item => item.CreateDateTime);
            }
            else if (type == ArticleQueryType.Category)
            {
                articleDtos = articleService.Query(x => x.Category.Id == id && !x.IsDeleted, x => x.CreateDateTime);
            }
            else if (type == ArticleQueryType.Tag)
            {
                articleDtos = articleService.get_article_by_tag(id.Value);
            }

            ViewBag.Tags = tagService.Query(item => !item.IsDeleted, item => item.Id, false);
            return View(articleDtos);
        }

        public ActionResult BookMarks()
        {
            var userdto = provider.GetAuthorizeUser();
            return View(userdto.BookMarks.ToList());
        }

        [HttpPost]
        public ActionResult BookMark(int id)
        {
            var user = provider.GetAuthorizeUser();
            var article = articleService.get_by_id(id);
            if (user.BookMarks==null)
            {
                user.BookMarks=new List<ArticleDto>();
            }
            user.BookMarks.Add(article);
            userService.Update(user);
            return RedirectToAction("BookMarks");
        }

        [HttpPost]
        public ActionResult LikedNote(int id)
        {
            var user = provider.GetAuthorizeUser();
            var article = articleService.get_by_id(id);
            if (user.LikedNotes == null)
            {
                user.LikedNotes = new List<ArticleDto>();
            }
            user.LikedNotes.Add(article);
            userService.Update(user);
            return RedirectToAction("LikedNotes");
        }


        public ActionResult LikedNotes()
        {
            var userdto = provider.GetAuthorizeUser();
            return View(userdto.LikedNotes.ToList());
        }

        public ActionResult Detial(int id)
        {
            articleService.add_view(id);
            var article = articleService.get_by_id(id);
            return View(article);
        }

        [ChildActionOnly]
        public ActionResult AuthorInfo()
        {
            return View("_AuthorInfo");
        }

        [ChildActionOnly]
        public ActionResult TagList()
        {
            var tags = tagService.Query(item => !item.IsDeleted, item => item.Id, false);
            return View("_TagList", tags);
        }

        [ChildActionOnly]
        public ActionResult HotArticle()
        {
            var articleDtos = articleService.Query(x => !x.IsDeleted, y => y.Views, true, 5);
            return View("_HotArticle", articleDtos);
        }

        [ChildActionOnly]
        public ActionResult FriendLinkList()
        {
            var dtos = friendly_link_service.QueryAll();
            return View("_FriendLinkList", dtos);
        }

        [ChildActionOnly]
        public ActionResult Carousel()
        {
            //文章需要加入图片
            //var dtos = friendly_link_service.QueryAll();
            return View("_Carousel");
        }

        [ChildActionOnly]
        public ActionResult Recommend()
        {
            var articleDto = articleService.Query(x => !x.IsDeleted, y => y.Views, true, 1).FirstOrDefault();
            return View("_Recommend", articleDto);
        }
    }
}

XCode.RuningCode/XCode.RuningCode.Web/Controllers/UserController.cs
using System.Web.Mvc;
using XCode.RuningCode.Core.Extentions;
using XCode.RuningCode.Service.Abstracts;
using XCode.RuningCode.Service.Dto;

namespace XCode.RuningCode.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;
        private readonly IAuthorizeProvider provider;

        public UserController(IUserService userService, IAuthorizeProvider provider)
        {
            this.userService = userService;
            this.provider = provider;
        }

        [HttpGet, AllowAnonymous]
        public ActionResult SignIn()
        {
            return View();
        }

        [HttpPost, AllowAnonymous]
        public ActionResult SignIn(SignInDto model)
        {
            provider.SignIn(model);
            if (userService.SignIn(model.UserName, model.Password.ToMD5()))
            {
                provider.SignIn(model);
                return RedirectToAction("Index", "Blog");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "无效的用户名或密码");
            }
            return View();
        }

        public ActionResult Logout()
        {
            if (User.Identity.IsAuthenticated)
            {
                provider.SignOut();
            }
            return RedirectToAction("SignIn");
        }

        [AllowAnonymous]
        public ActionResult ForgotPwd()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Reg()
        {
            return View();
        }
    }
}

XCode.RuningCode/XCode.RuningCode.Web/Views/Shared/BaiduTongji.cshtml
<script>
    var _hmt = _hmt || [];
    (function() {
      var hm = document.createElement("script");
      hm.src = "//hm.baidu.com/hm.js?7183a90d68b58b5c1d7bea65d3ca68e1";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(hm, s);
    })();
</script>

XCode.RuningCode/XCode.RuningCode.Web/Views/Shared/_ArticleCommonList.cshtml
@using XCode.RuningCode.Service.Dto.Blog
@{
    Layout = null;
}
@model List<ArticleDto>
    
@foreach (var article in Model)
            {
    <article class="excerpt excerpt-1" style="">
        <a class="focus" href="" title="@article.Title" target="_blank"><img class="thumb" data-original="/Template/front/web/images/slider/bg2.jpg" src="/Template/front/web/images/slider/bg2.jpg" alt="@article.Title" style="display: inline;"></a>
        <header>
            <a class="cat" href="" title="@article.Category.Name">@article.Category.Name<i></i></a>
            <h2>
                <a href="@Url.Action("Detial", "Blog", new {id = article.Id})" title="@article.Title" target="_blank">@article.Title</a>
            </h2>
        </header>
        <p class="note">@article.Content</p>
        <p class="meta">
            <time class="time"><i class="glyphicon glyphicon-time"></i> @article.CreateDateTime</time>
            <span class="views"><i class="glyphicon glyphicon-eye-open"></i> @article.Views</span> <a class="comment" href="" title="评论" target="_blank"><i class="glyphicon glyphicon-comment"></i> @article.CommentCount</a>
            @if (article.Author != null)
                {
                <span><a href="">@article.Author.RealName</a></span>
            }
        </p>
    </article>
}
@*<nav class="pagination" style="display: none;">
        <ul>
            <li class="prev-page"></li>
            <li class="active"><span>1</span></li>
            <li><a href="?page=2">2</a></li>
            <li class="next-page"><a href="?page=2">下一页</a></li>
            <li><span>共 2 页</span></li>
        </ul>
    </nav>*@

XCode.RuningCode/XCode.RuningCode.Web/Views/Shared/_ArticleList.cshtml
@using XCode.RuningCode.Core.Enums
@using XCode.RuningCode.Service.Dto.Blog
@{
    List<CategoryDto> catrgories = ViewBag.Categories;
    Layout = null;
}
@model List<ArticleDto>

<div>
    <div class="title">
        <h3>最新发布</h3>
        <div class="more">
            @foreach (var category in catrgories)
            {
                <a href="@Url.Action("Index", "Blog", new { type=ArticleQueryType.Category,id = category.Id})" title="@category.Name">@category.Name</a>
            }
        </div>
    </div>

    @Html.Partial("_ArticleCommonList", Model)
</div>

XCode.RuningCode/XCode.RuningCode.Web/Views/Shared/_AuthorInfo.cshtml
@{
    Layout = null;
}

<div class="fixed">
    <div class="widget widget-tabs">
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#notice" aria-controls="notice" role="tab" data-toggle="tab">统计信息</a></li>
            <li role="presentation"><a href="#contact" aria-controls="contact" role="tab" data-toggle="tab">联系站长</a></li>
        </ul>
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane contact active" id="notice">
                <h2>
                    日志总数:
                    888篇
                </h2>
                <h2>
                    网站运行:
                    <span id="sitetime">88天 </span>
                </h2>
            </div>
            <div role="tabpanel" class="tab-pane contact active" id="contact">
                <h2>
                    QQ:
                    <a href="http://wpa.qq.com/msgrd?v=3&amp;uin=278100426&amp;site=qq&amp;menu=yes" target="_blank" rel="nofollow" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="QQ:278100426">278100426</a>
                </h2>
                <h2>
                    Email:
                    <a href="mailto:278100426@qq.com" target="_blank" data-toggle="tooltip" rel="nofollow" data-placement="bottom" title="" data-original-title="Email:278100426@qq.com">278100426@qq.com</a>
                </h2>
            </div>
        </div>
    </div>
    <div class="widget widget_search">
        <form class="navbar-form" action="/Search" method="post">
            <div class="input-group">
                <input type="text" name="keyword" class="form-control" size="35" placeholder="请输入关键字" maxlength="15" autocomplete="off">
                <span class="input-group-btn">
                    <button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
                </span>
            </div>
        </form>
    </div>
</div>

XCode.RuningCode/XCode.RuningCode.Web/Views/Shared/_Carousel.cshtml
@{
    Layout = null;
}

<div id="focusslide" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#focusslide" data-slide-to="0" class="active"></li>
        <li data-target="#focusslide" data-slide-to="1"></li>
        <li data-target="#focusslide" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="/Template/front/web/images/slider/bg1.jpg" alt="First slide">
        </div>
        <div class="item">
            <img src="/Template/front/web/images/slider/bg2.jpg" alt="Second slide">
        </div>
        <div class="item">
            <img src="/Template/front/web/images/slider/bg3.jpg" alt="Second slide">
        </div>
    </div>
    <a class="left carousel-control" href="#focusslide" role="button" data-slide="prev" rel="nofollow"> <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <span class="sr-only">上一个</span> </a> <a class="right carousel-control" href="#focusslide" role="button" data-slide="next" rel="nofollow"> <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> <span class="sr-only">下一个</span> </a>
</div>

XCode.RuningCode/XCode.RuningCode.Web/Views/Shared/_FriendLinkList.cshtml
@using XCode.RuningCode.Service.Dto
@model IList<FriendlyLinkDto>
@{
    Layout = null;
}
<div class="widget widget_sentence">
    <h3>友情链接</h3>
    @if (Model.Any())
    {
        foreach (var friendly_link_dto in Model)
        {
            <div style="padding: 15px; cursor: pointer">
                <a href="@friendly_link_dto.Link" title="@friendly_link_dto.Title" target="_blank">@friendly_link_dto.Name</a>&nbsp;&nbsp;&nbsp;
            </div>
        }
    }

</div>

XCode.RuningCode/XCode.RuningCode.Web/Views/Shared/_HotArticle.cshtml
@model List<XCode.RuningCode.Service.Dto.Blog.ArticleDto>

@{
    Layout = null;
}

<div class="widget widget_hot">
    <h3>最热文章</h3>
    <ul>
        @foreach (var article in Model)
        {
            <li>
                <a title="@article.Title" href="">
                    <span class="thumbnail">
                        <img class="thumb" data-original="/Template/front/web/images/slider/bg2.jpg" src="/Template/front/web/images/slider/bg2.jpg" alt="@article.Title" style="display: block;">
                    </span><span class="text">@article.Title</span><span class="muted">
                        <i class="glyphicon glyphicon-time"></i>
                        @article.CreateDateTime.ToString("yyyy-MM-dd")
                    </span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>@article.Views</span>
                </a>
            </li>
        }
    </ul>
</div>

XCode.RuningCode/XCode.RuningCode.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

XCode.RuningCode/XCode.RuningCode.Web/Views/Shared/_Layout_Content.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>XCode Blog</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" type="text/css" href="/Template/Test/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/Template/Test/css/nprogress.css">
    <link rel="stylesheet" type="text/css" href="/Template/Test/css/style.css">
    <link rel="stylesheet" type="text/css" href="/Template/Test/css/xcode.scss">
    <link rel="stylesheet" type="text/css" href="/Template/Test/css/font-awesome.min.css">
    <link rel="apple-touch-icon-precomposed" href="/Template/Test/images/icon.png">
    <link href="/Template/Admin/jucheap/Js/switchery/switchery.min.css" rel="stylesheet" type="text/css" media="screen" />
    <link rel="shortcut icon" href="/Template/Test/images/favicon.ico">
    <script src="/Template/Test/js/jquery-2.1.4.min.js"></script>
    <script src="/Template/Test/js/nprogress.js"></script>
    <script src="/Template/Test/js/jquery.lazyload.min.js"></script>
</head>
<body class="user-select">
    <header class="header">
        <nav class="navbar navbar-default navbar-fixed-top" id="navbar">
            <div class="container">
                <div class="navbar-header">
                    <h1 class="logo hvr-bounce-in">
                        <a href="@Url.Action("Index", "Blog")" title="XCode"><img src="/Template/Test/images/logo.png" alt="XCode Blog"></a>
                    </h1>
                </div>
                <div class="collapse navbar-collapse" id="header-navbar">
                    <!--为什么这个搜索框没出来-->
                    <form class="navbar-form visible-xs" action="" method="post">
                        <div class="input-group">
                            <input type="text" name="keyword" class="form-control" placeholder="请输入关键字" maxlength="20" autocomplete="off">
                            <span class="input-group-btn">
                                <button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
                            </span>
                        </div>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a data-cont="XCode" title="首页" href="@Url.Action("Index", "Blog")">首页</a></li>
                        @if (!@HttpContext.Current.User.Identity.IsAuthenticated)
                        {
                            <li><a data-cont="XCode" title="登录" href="@Url.Action("SignIn", "User")">登录</a></li>
                            <li><a data-cont="XCode" title="注册" href="@Url.Action("Reg", "User")">注册</a></li>
                        }
                        else
                        {
                            <li>
                                <div>
                                    <a href="javascript:;" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    <img src="/Template/Admin/jucheap/img/avatar-mini.jpg" alt="">
                                    <span class="fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu purple pull-right">
                                    <li><a href="javascript:;"> 我的主页</a></li>
                                    <li><a href="@Url.Action("Index", "Control", new {Area = "Adm"})"> 我的管理</a></li>
                                    <li><a href="@Url.Action("BookMarks", "Blog")"> 收藏的文章</a></li>
                                    <li><a href="@Url.Action("LikedNotes", "Blog")"> 喜欢的文章</a></li>
                                    <li><a href="javascript:;"> 设置</a></li>
                                    <li><a href="@Url.Action("Logout", "User")"><i class="fa fa-sign-out pull-left"></i> 注销</a></li>
                                </ul>
                                </div>
                                
                            </li>
                        }
                        <li><a data-cont="XCode" title="写文章" href="@Url.Action("Add", "Article")">写文章</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <section class="container">
        @RenderBody()
    </section>
    <footer style="clear: both;padding: 24px 15px;font-size: 12px;line-height: 12px;text-align: center;text-transform: uppercase;color: #999;background-color: #FFF;">
        <div class="container">
            <p>本站[<a href="http://www.x-code.me">XCode Blog</a>]的部分内容来源于网络，若侵犯到您的利益，请联系站长删除！谢谢！Powered By [<a href="http://www.x-code.me/" target="_blank" rel="nofollow">XCode</a>] Version 4.0 &nbsp;<a href="http://www.miitbeian.gov.cn/" target="_blank" rel="nofollow">闽ICP备00000000号-1</a> &nbsp; <a href="" target="_blank" class="">网站地图</a></p>
        </div>
        @*<div id="gotop"><a class="gotop"></a></div>*@
    </footer>
    <script src="/Template/Test/js/bootstrap.min.js"></script>
    <script src="/Template/Test/js/jquery.ias.js"></script>
    <script src="/Template/Test/js/scripts.js"></script>
</body>
</html>

XCode.RuningCode/XCode.RuningCode.Web/Views/Shared/_Layout_XCode.cshtml
@using System.Web.Optimization

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <meta name="author" content="dj.wong" />
    <meta name="keywords" content="JuCheap后台管理模板,C# MVC Bootstrap 后台管理模板" />
    <meta name="description" content="JuCheap后台管理模板,采用MVC+EF+Bootstrap构建了一套自适应的通用后台管理模板;JuCheap后台管理模板,已经实现了用户管理,菜单管理,权限管理和日志管理功能.JuCheap后台管理模板使用的技术包括:C#,MVC,EF,Jquery,Bootstrap,jqGrid,DDD,AutoMapper等.JuCheap使用到的技术完全开源,适合快速的搭建后台管理框架,支持自定义扩展." />

    <title>@ViewBag.Title - JuCheap后台管理模板</title>

    @RenderSection("StylesBefore", false)
    
    <!--common style-->
    @Styles.Render("~/Template/Admin/jucheap/Css/BaseStyles")

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <style>
        .row{margin: 0;}
    </style>

    @RenderSection("StylesAfter", false)
    @Html.Partial("BaiduTongji")
</head>
<body style="background-color: inherit;">

    @RenderBody()

    @Scripts.Render("~/JS/Admin/jucheap/BaseScripts")
    @Scripts.Render("~/JS/Admin/jucheap/JuCheap")

    @RenderSection("Scripts", false)
</body>
</html>

XCode.RuningCode/XCode.RuningCode.Web/Views/Shared/_TagList.cshtml
@using XCode.RuningCode.Core.Enums
@model List<XCode.RuningCode.Service.Dto.Blog.TagDto>

@{
    Layout = null;
}

<div class="fixed">
    <div class="widget widget-tabs">
        <div class="tab-content">
            <h2 class="title">标签云</h2>
            <ul>
                @foreach (var tag in Model)
                {
                    <a href="@Url.Action("Index", "Blog", new { type=ArticleQueryType.Tag,id = tag.Id})" title="@tag.Name">@tag.Name</a>
                }
            </ul>
        </div>
    </div>
</div>